export const MapLayout = {
  TREE_HORIZONTAL: 'Tree (Horizontal)',
  TREE_VERTICAL: 'Tree (Vertical)',
  STANDARD: 'Standard (Split)',
  RADIAL: 'Radial (Burst)',
  ORGANIC: 'Organic (Force)',
  FISHBONE: 'Fishbone (Timeline)',
  SPIRAL: 'Galaxy (Spiral)',
};

export const MapTheme = {
  DEFAULT: 'Classic',
  HAND_DRAWN: 'Sticky Notes',
  PROFESSIONAL: 'Concept Map',
  BUBBLE: 'Creative Bubbles',
  DARK_NEON: 'Dark Neon',
  NATURE: 'Forest',
  CYBERPUNK: 'Cyberpunk',
  MONOCHROME: 'Monochrome',
  RETRO: 'Retro Vibe',
  BLUEPRINT: 'Blueprint',
  MINIMAL: 'Minimalist',
  GLASS: 'Glassmorphism',
  PLAYFUL: 'Playful Pop',
  CORPORATE: 'Corporate',
  WARM: 'Warm Sunset',
  SPACE: 'Deep Space',
  VINTAGE: 'Vintage Paper',
  GAME: '8-Bit Retro',
  COMIC: 'Comic Book',
  CRYSTAL: 'Crystal Shard',
  CANDY: 'Cotton Candy',
  NOIR: 'Film Noir',
  JUNGLE: 'Deep Jungle',
  MAGMA: 'Volcanic Magma',
  HACKER: 'Terminal Hacker',
  ROYAL: 'Royal Gold',
  TERMINAL_AMBER: 'Retro Monitor',
  LOVERS: 'Romantic',
  SPOOKY: 'Spooky Night',
  AQUA: 'Ocean Flow'
};
